module : segmentationUnet.Segmentation
model :   unet_2d.OriginalUNet
dataset : us_dataset.AortaDataset
n_classes : 1
data_root : ../imgs
batch_size : 1
output_path : ../Logs/
early_stopping_metric : val_loss  #val_loss  #default
save_top_k : 1
min_epochs : 30
max_epochs : 100
num_sanity_val_steps : 0 #default 2
log_interval : 100 #default
log_every_n_steps : 10 #default is 5
limit_train : 1.0 #1.0 default
limit_val : 1.0
nr_train_folds : 3
#on_polyaxon : False
polyaxon_data_path : ../cluster/data
#cross_val : False

